apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ts-vite-bootstrap-starter
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: react-ts-vite-bootstrap-starter
        resources:
            limits:
              cpu: 1000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 128Mi