version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "07:00"
      timezone: "Europe/Bucharest"
    allow:
      - dependency-type: direct
        update-type: "version-update:semver-minor"
      - dependency-type: direct
        update-type: "version-update:semver-patch"
    versioning-strategy: increase