version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /
    schedule:
    #      interval: daily
      days: [ monday, tuesday, wednesday, friday ]
    #      time: 7:00
    #      timezone: Europe/Bucharest
    allow:
      - dependency-type: direct
        update-types: [ "version-update:semver-minor", "version-update:semver-patch" ]
    versioning-strategy: increase