apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-cluster-binding
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: default
roleRef:
  kind: ClusterRole
  name: github-actions-cluster-role
  apiGroup: rbac.authorization.k8s.io