name: Build and Deploy to Kubernetes

on:
#  push:
#    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  GITHUB_SHA_SHORT: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set short SHA
        run: echo "GITHUB_SHA_SHORT=$(echo ${{ github.sha }} | head -c 7)" >> $GITHUB_ENV

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Skaffold
        run: |
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin

      - name: Set up Kubernetes context
      - uses: azure/k8s-set-context@v4
        with:
          method: service-account
          k8s-url: ${{ secrets.K8S_API_SERVER }}
          k8s-secret: ${{ secrets.K8S_TOKEN }}

#      - name: Build and push Docker image with Skaffold
#        run: |
#          skaffold build --push=true \
#            --default-repo=${{ env.REGISTRY }}/${{ github.actor }} \
#            --tag=${{ env.GITHUB_SHA_SHORT }}
#
#      - name: Deploy to Kubernetes with Skaffold
#        run: |
#          skaffold run --profile pp --default-repo=${{ env.REGISTRY }}/${{ github.actor }} \
#            --tag=${{ env.GITHUB_SHA_SHORT }}

      - name: Verify deployment
        run: kubectl get pods