name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allows pushing code to the repository
      pull-requests: write  # Allows merging PRs
      issues: write  # Allows creating and managing issues
      packages: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto-merge dependabot PR
        if: github.actor == 'dependabot[bot]'
        uses: pascalgn/automerge-action@v0.15.3
        with:
          merge-method: squash