name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Auto-merge dependabot PR
#        if: github.actor == 'dependabot[bot]'
        run: echo ${{ github.actor }}
#        uses: pascalgn/automerge-action@v0.16.4
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"