name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    if: |
      github.actor == 'dependabot[bot]' &&
      github.event.pull_request.state == 'open' &&
      github.event.pull_request.base.ref == 'master'

    steps:
      - name: Approve the PR
        run: |
          gh pr review ${{ github.event.pull_request.html_url }} --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge
        run: |
          gh pr merge ${{ github.event.pull_request.html_url }} --merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}